[package]
name = "podlet"
version = "0.2.0"
authors = ["Paul Nettleton <k9@k9withabone.dev>"]
edition = "2021"
description = "Podlet generates podman quadlet (systemd-like) files from a podman command."
readme = "README.md"
repository = "https://github.com/k9withabone/podlet"
license = "MPL-2.0"
keywords = ["podman", "quadlet"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.2", features = ["derive"] }
color-eyre = "0.6"
docker-compose-types = "0.5.1"
duration-str = { version = "0.7", default-features = false }
indexmap = "2"
ipnet = "2.7"
k8s-openapi = { version = "0.20", features = ["latest"] }
serde_yaml = "0.9.21"
shlex = "1.1"
thiserror = "1.0.40"
url = "2.3"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.26", features = ["user"], default-features = false }
zbus = "3.12"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.70.0"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
# The installers to generate for each app
installers = []
